"""add_skills_table

Revision ID: b3ce2589d775
Revises: cb8c1f67cd6c
Create Date: 2026-04-30 15:05:18.587160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3ce2589d775'
down_revision: Union[str, None] = 'cb8c1f67cd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_skill_owner_name')
    )
    with op.batch_alter_table('core_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_skills_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_core_skills_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_skills_owner_id'))
        batch_op.drop_index(batch_op.f('ix_core_skills_id'))

    op.drop_table('core_skills')
    # ### end Alembic commands ###

